# Generated by Django 3.2.8 on 2022-03-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Não Informado')], default='O', max_length=1, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, choices=[('UP', 'Professor'), ('UW', 'Técnico Administrativo'), ('US', 'Estudante'), ('UC', 'Membro da Comunidade')], max_length=2, null=True, verbose_name='Perfil'),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='page-slug', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
