# Generated by Django 3.2.8 on 2022-03-23 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0002_auto_20220323_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['full_name'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
