# Generated by Django 3.2.8 on 2022-03-28 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-full_name'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
