version: '3.3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  
  db:
    image: postgres:13.0-alpine
    container_name: pgdb
    volumes:
      - pgdb:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sigprae
      - POSTGRES_PASSWORD=sigprae
      - POSTGRES_DB=sigprae
    ports:
      - 5433:5432

volumes:
  pgdb: 