# Generated by Django 4.0.3 on 2022-12-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interestarea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestarea',
            name='slug',
            field=models.SlugField(default='123456', max_length=6, unique=True),
        ),
    ]
