# Generated by Django 4.1.4 on 2023-01-03 23:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_delete_interestarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0cbed61e-e8c5-4021-9b5f-0358183d853f'), editable=False),
        ),
    ]
