# Generated by Django 4.1.4 on 2023-01-03 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0e2228e9-ef36-45ef-81af-4aedad281b5d'), editable=False),
        ),
    ]
