# Generated by Django 4.1.4 on 2023-01-03 23:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('a7e485d3-bf37-42a0-ad74-35f6ed400f0c'), editable=False),
        ),
    ]
