# Generated by Django 4.1.4 on 2023-01-03 23:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('78b763ea-6301-4613-8651-ea26e33b6796'), editable=False),
        ),
    ]
