# Generated by Django 4.1.4 on 2023-01-05 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0006_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0d00405f-d031-49c6-b199-6015b497ca39'), editable=False),
        ),
    ]
