# Generated by Django 4.1.4 on 2023-01-05 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interestarea', '0015_alter_interestarea_uuid'),
        ('subject', '0007_alter_subject_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='instestareas',
            field=models.ManyToManyField(related_name='subjects', to='interestarea.interestarea'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('6a66f5bb-f2eb-4dad-bb9d-59ef1fe96930'), editable=False),
        ),
    ]
