# Generated by Django 4.1.4 on 2023-01-10 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0011_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('ca8b19d4-d4a0-4b40-877f-b1c1d897f266'), editable=False),
        ),
    ]
