# Generated by Django 4.1.4 on 2023-01-09 23:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0013_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('99513698-1701-4983-a547-75f520f9cdfd'), editable=False),
        ),
    ]
