# Generated by Django 4.1.4 on 2023-01-09 23:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0014_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('02543e82-c166-45f7-9128-813ea09bab43'), editable=False),
        ),
    ]
