# Generated by Django 4.1.4 on 2023-01-18 23:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0015_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('dd9c2657-505b-4130-9d7f-0f1ed0153a67'), editable=False),
        ),
    ]
