# Generated by Django 4.1.4 on 2023-01-18 23:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0016_alter_subject_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('e120b314-21fd-4415-b218-b83485824d78'), editable=False),
        ),
    ]
