# Generated by Django 4.0.3 on 2022-05-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_subject_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='categories',
            field=models.ManyToManyField(to='category.category'),
        ),
    ]
