# Generated by Django 4.1.4 on 2022-12-20 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interestarea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestarea',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('416667e1-7641-46e9-8226-51a2c04436fc'), editable=False),
        ),
    ]
