# Generated by Django 4.1.4 on 2023-01-03 23:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interestarea', '0002_alter_interestarea_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestarea',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('6b09bbb1-7c4c-456d-9727-0e80c61bf5d8'), editable=False),
        ),
    ]
