# Generated by Django 4.1.4 on 2023-01-03 23:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interestarea', '0003_alter_interestarea_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestarea',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('272e6781-e3a4-4ea9-a53a-fcc737abb914'), editable=False),
        ),
    ]
