# Generated by Django 4.1.4 on 2023-01-03 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interestarea', '0005_alter_interestarea_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestarea',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('876ccdd2-bee8-4b1b-8428-3bb19d716862'), editable=False),
        ),
    ]
