# Generated by Django 4.1.4 on 2023-01-03 23:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interestarea', '0006_alter_interestarea_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestarea',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('a2155a24-8010-44b9-b3e8-3b0fa8d6628f'), editable=False),
        ),
    ]
