# Generated by Django 4.1.4 on 2023-01-03 23:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interestarea', '0009_alter_interestarea_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestarea',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('a20bdaed-ca2e-436f-a83e-b7c582e064a5'), editable=False),
        ),
    ]
