# Generated by Django 4.1.4 on 2023-01-03 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interestarea', '0010_alter_interestarea_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestarea',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('8ad2d163-9a78-4ac9-abdb-6e214bcce291'), editable=False),
        ),
    ]
