# Generated by Django 4.1.4 on 2023-01-03 23:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interestarea', '0012_alter_interestarea_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestarea',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('8cf9dae7-f03f-4f5d-b1dd-f6901e358f2a'), editable=False),
        ),
    ]
