# Generated by Django 4.1.4 on 2023-01-05 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interestarea', '0013_alter_interestarea_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestarea',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('e06b42ab-4aaa-4098-86a0-b720e4296ed5'), editable=False),
        ),
    ]
