# Generated by Django 4.1.4 on 2023-01-05 16:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interestarea', '0014_alter_interestarea_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestarea',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('65d13972-ac4f-430a-a1c3-935fed6b199b'), editable=False),
        ),
    ]
