# Generated by Django 4.1.4 on 2023-01-09 23:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interestarea', '0020_alter_interestarea_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestarea',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('13f8ebcc-ed60-4bfc-9ef2-a0f475fb34d2'), editable=False),
        ),
    ]
