# Generated by Django 4.1.4 on 2023-01-09 23:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interestarea', '0021_alter_interestarea_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestarea',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('69302e91-5988-4993-a71d-cce0029890bf'), editable=False),
        ),
    ]
