# Generated by Django 4.1.4 on 2023-01-18 23:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interestarea', '0022_alter_interestarea_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestarea',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('5c4550b6-c991-4882-97dd-db7b99082fe3'), editable=False),
        ),
    ]
