# Generated by Django 4.1.4 on 2023-01-18 23:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interestarea', '0023_alter_interestarea_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestarea',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('9b9965a4-e8c1-441d-878a-d27faec02e89'), editable=False),
        ),
    ]
